// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class HealthSystemAttackEventHandler {
        
        public Player Group;
        
        private test.AttackEvent _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private test.AttackEvent PublishEventNode1_Result = default( test.AttackEvent );
        
        public test.AttackEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("","8db86060-7116-447c-8f93-aa1efa9d7b06", this) == 1) yield return null;
            var PublishEventNode1_Event = new AttackEvent();
            System.Publish(PublishEventNode1_Event);
            PublishEventNode1_Result = PublishEventNode1_Event;
            yield break;
        }
    }
}
