// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.UnityUtilities;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class InputSystemOnMouseDownHandler {
        
        public HealthComponent Source;
        
        private uFrame.ECS.UnityUtilities.MouseDownDispatcher _Event;
        
        private uFrame.ECS.Systems.EcsSystem _System;
        
        private int ActionNode4_a = default( System.Int32 );
        
        private int ActionNode4_b = default( System.Int32 );
        
        private int IntNode3 = 10;
        
        private int ActionNode4_Result = default( System.Int32 );
        
        private object ActionNode8_a = default( System.Object );
        
        private object ActionNode8_b = default( System.Object );
        
        private int IntNode9 = 0;
        
        private bool ActionNode8_Result = default( System.Boolean );
        
        private UnityEngine.GameObject ActionNode10_gameObject = default( UnityEngine.GameObject );
        
        private int ActionNode12_in = default( System.Int32 );
        
        private int IntNode11 = 0;
        
        private float ActionNode12_Result = default( System.Single );
        
        private float ActionNode10_time = default( System.Single );
        
        private object ActionNode13_message = default( System.Object );
        
        public uFrame.ECS.UnityUtilities.MouseDownDispatcher Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.Systems.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            ActionNode4_a = Source.health;
            ActionNode4_b = IntNode3;
            // ActionNode
            // Visit uFrame.ECS.Actions.IntLibrary.Subtract
            ActionNode4_Result = uFrame.ECS.Actions.IntLibrary.Subtract(ActionNode4_a, ActionNode4_b);
            // SetVariableNode
            Source.health = (System.Int32)ActionNode4_Result;
            ActionNode8_a = Source.health;
            ActionNode8_b = IntNode9;
            // ActionNode
            // Visit uFrame.ECS.Actions.Comparisons.AreEqual
            ActionNode8_Result = uFrame.ECS.Actions.Comparisons.AreEqual(ActionNode8_a, ActionNode8_b, ActionNode8_yes, ActionNode8_no);
            ActionNode13_message = Source.health;
            // ActionNode
            // Visit uFrame.ECS.Actions.DebugLibrary.LogMessage
            uFrame.ECS.Actions.DebugLibrary.LogMessage(ActionNode13_message);
        }
        
        private void ActionNode8_yes() {
            ActionNode10_gameObject = Source.gameObject;
            ActionNode12_in = IntNode11;
            // ActionNode
            // Visit uFrame.ECS.Actions.Converter.IntToFloat
            ActionNode12_Result = uFrame.ECS.Actions.Converter.IntToFloat(ActionNode12_in);
            ActionNode10_time = ActionNode12_Result;
            // ActionNode
            // Visit uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject
            uFrame.ECS.Actions.DestroyLibrary.DestroyGameObject(ActionNode10_gameObject, ActionNode10_time);
        }
        
        private void ActionNode8_no() {
        }
    }
}
