// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using test;
    using uFrame.ECS.APIs;
    using uFrame.ECS.Components;
    using uFrame.ECS.Systems;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class InputSystemBase : uFrame.ECS.Systems.EcsSystem {
        
        private IEcsComponentManagerOf<Player> _PlayerManager;
        
        private IEcsComponentManagerOf<HealthComponent> _HealthComponentManager;
        
        private InputSystemOnMouseDownHandler InputSystemOnMouseDownHandlerInstance = new InputSystemOnMouseDownHandler();
        
        public IEcsComponentManagerOf<Player> PlayerManager {
            get {
                return _PlayerManager;
            }
            set {
                _PlayerManager = value;
            }
        }
        
        public IEcsComponentManagerOf<HealthComponent> HealthComponentManager {
            get {
                return _HealthComponentManager;
            }
            set {
                _HealthComponentManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            PlayerManager = ComponentSystem.RegisterComponent<Player>(3);
            HealthComponentManager = ComponentSystem.RegisterComponent<HealthComponent>(2);
            this.OnEvent<uFrame.ECS.UnityUtilities.MouseDownDispatcher>().Subscribe(_=>{ InputSystemOnMouseDownFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void InputSystemOnMouseDownHandler(uFrame.ECS.UnityUtilities.MouseDownDispatcher data, HealthComponent source) {
            var handler = InputSystemOnMouseDownHandlerInstance;
            handler.System = this;
            handler.Event = data;
            handler.Source = source;
            StartCoroutine(handler.Execute());
        }
        
        protected void InputSystemOnMouseDownFilter(uFrame.ECS.UnityUtilities.MouseDownDispatcher data) {
            var SourceHealthComponent = HealthComponentManager[data.EntityId];
            if (SourceHealthComponent == null) {
                return;
            }
            if (!SourceHealthComponent.Enabled) {
                return;
            }
            this.InputSystemOnMouseDownHandler(data, SourceHealthComponent);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("5ed70f54-d859-4028-aa87-9548adf59b22")]
    public partial class InputSystem : InputSystemBase {
        
        private static InputSystem _Instance;
        
        public InputSystem() {
            Instance = this;
        }
        
        public static InputSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
