// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace test {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.ECS.Components;
    using uFrame.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(2)]
    [uFrame.Attributes.uFrameIdentifier("5202508c-8dce-42aa-ba73-2b9a862edca9")]
    public partial class HealthComponent : uFrame.ECS.Components.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Int32 _health;
        
        private Subject<PropertyChangedEvent<Int32>> _healthObservable;
        
        private PropertyChangedEvent<Int32> _healthEvent;
        
        public override int ComponentId {
            get {
                return 2;
            }
        }
        
        public IObservable<PropertyChangedEvent<Int32>> healthObservable {
            get {
                return _healthObservable ?? (_healthObservable = new Subject<PropertyChangedEvent<Int32>>());
            }
        }
        
        public Int32 health {
            get {
                return _health;
            }
            set {
                Sethealth(value);
            }
        }
        
        public virtual void Sethealth(Int32 value) {
            SetProperty(ref _health, value, ref _healthEvent, _healthObservable);
        }
    }
}
